apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    run: nginx-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30063
    protocol: TCP
  selector:
    app: guestbook
    tier: frontend
